
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = armijo.c
SOURCEF  = 
SOURCEH  = armijo.h
OBJSC    = armijo.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/linesearch/impls/armijo/

include ${TAO_DIR}/bmake/tao_common

