
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taois_petsc.c
SOURCEF  = 
SOURCEH  = taois_petsc.h
OBJSC    = taois_petsc.o
OBJSF    = 
LIBBASE  = libtaopetsc
MANSEC   = ptaopages
LOCDIR   = src/petsctao/indexset/

include ${TAO_DIR}/bmake/tao_common


