ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = kt.c
SOURCEF  = 
SOURCEH  = kt.h
OBJSC    = kt.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/bound/impls/kt/

include ${TAO_DIR}/bmake/tao_common

