# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ntr.c
SOURCEF  = 
SOURCEH  = ntr.h
OBJSC    = ntr.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/unconstrained/impls/ntr/

include ${TAO_DIR}/bmake/tao_common

