
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = daelement.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = daelement.o
OBJSF    = 
LIBBASE  = libtaopetsc
MANSEC   = daapp
LOCDIR   = src/petsctao/gridapplication/element/

include ${TAO_DIR}/bmake/tao_common


