
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ssls.c ssils.c ssfls.c
SOURCEF  = 
SOURCEH  = ssls.h
OBJSC    = ssls.o ssils.o ssfls.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/complementarity/impls/ssls/

include ${TAO_DIR}/bmake/tao_common

