
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = blmvm.c
SOURCEF  = 
SOURCEH  = blmvm.h
OBJSC    = blmvm.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/bound/impls/blmvm/

include ${TAO_DIR}/bmake/tao_common

