
ALL: lib

CPPFLAGS = -DTAO_LIB_DIR='"${TAO_LIB_DIR}"'
FFLAGS   =
SOURCEC  = petsckernel.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = petsckernel.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/petsctao/sys/

include ${TAO_DIR}/bmake/tao_common
