
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taoappobject.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = taoappobject.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = taoapp
LOCDIR   = src/appobject/interface/

include ${TAO_DIR}/bmake/tao_common


