# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ztao.c taopetsc.c ztao_start.c ztao_startf.c zpetsc_kernel.c
SOURCEF  = taofort.F
SOURCEH  = 
OBJSC    = ztao.o taopetsc.o ztao_start.o ztao_startf.o zpetsc_kernel.o
OBJSF    = taofort.o
LIBBASE  = libtaofortran
MANSEC   = solver
LOCDIR   = src/fortran/custom/

include ${TAO_DIR}/bmake/tao_common


