
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taolinearsolver_petsc.c 
SOURCEF  = 
SOURCEH  = taolinearsolver_petsc.h
OBJSC    = taolinearsolver_petsc.o
OBJSF    = 
LIBBASE  = libtaopetsc
MANSEC   = ptaopages
LOCDIR   = src/petsctao/linearsolver/

include ${TAO_DIR}/bmake/tao_common


