
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taolinearsolver.c taomatselfsolver.c
SOURCEF  = 
SOURCEH  = taomatselfsolver.h
OBJSC    = taolinearsolver.o taomatselfsolver.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = lsolver
LOCDIR   = src/lsolver/

include ${TAO_DIR}/bmake/tao_common


