
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  = 
SOURCEH  = taopetsc.h
OBJSC    =
OBJSF    = 
LIBBASE  = libtaopetsc
MANSEC   = ptaopages
LOCDIR   = src/petsctao/include/

include ${TAO_DIR}/bmake/tao_common


