
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = qp.c
SOURCEF  = 
SOURCEH  = qp.h 
OBJSC    = qp.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = SOLVER
LOCDIR   = src/quadratic/impls/qpip/

include ${TAO_DIR}/bmake/tao_common

