
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = submatfree.c taomat_petsc.c pmat.c normalmat.c
SOURCEF  = 
SOURCEH  = submatfree.h taomat_petsc.h normalmat.h
OBJSC    = submatfree.o taomat_petsc.o pmat.o normalmat.o
OBJSF    = 
LIBBASE  = libtaopetsc
MANSEC   = ptaopages
LOCDIR   = src/petsctao/matrix/

include ${TAO_DIR}/bmake/tao_common


