ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = taoesiapp.c 
SOURCEF  = 
SOURCEH  = taoesiapp.h esiapplication.h
OBJSC    = taoesiapp.o
OBJSF    = 
LIBBASE  = libesitao
MANSEC   = esiman
LOCDIR   = src/externaltao/esitao/esisolver

include ${TAO_DIR}/bmake/tao_common


