ALL: lib


CFLAGS   = 
FFLAGS   =
SOURCEC  = taovec_esi.c taomat_esi.c taolinearsolver_esi.c taoesimethods.c
SOURCEF  = 
SOURCEH  = taovec_esi.h taomat_esi.h taolinearsolver_esi.h 
OBJSC    = taovec_esi.o taomat_esi.o taolinearsolver_esi.o taoesimethods.o
OBJSF    = 
LIBBASE  = libesitao
MANSEC   = esiman
LOCDIR   = src/externaltao/esitao/interface

include ${TAO_DIR}/bmake/tao_common


