# $Id: makefile,v 1.1 2007-06-12 15:11:28 sarich Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = neldermead.c
SOURCEF  = 
SOURCEH  = neldermead.h
OBJSC    = neldermead.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/unconstrained/impls/neldermead/

include ${TAO_DIR}/bmake/tao_common

