
ALL: lib

CPPFLAGS =
FFLAGS   =
SOURCEC  = bkernal.c 
SOURCEF  = 
SOURCEH  = 
OBJSC    = bkernal.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/sys/

include ${TAO_DIR}/bmake/tao_common


