
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taoabcapp.c taofloatapp.c
SOURCEF  = 
SOURCEH  = taoabcapp.h taofloatapp.h
OBJSC    = taoabcapp.o taofloatapp.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = taoapp
LOCDIR   = src/appobject/interface/

include ${TAO_DIR}/bmake/tao_common
