# $Id$

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = tao_mfj.c tao_mfjdef.c mfregis.c
SOURCEF  =
SOURCEH  = tao_mfj.h
OBJSC    = tao_mfj.o tao_mfjdef.o mfregis.o
OBJSF    =
LIBBASE  = libtao
MANSEC   = fd
DIRS     = 
LOCDIR   = src/supplementary/matrix/matrix_free

include ${TAO_DIR}/bmake/tao_common


