
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = morethuente.c
SOURCEF  = 
SOURCEH  = morethuente.h
OBJSC    = morethuente.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/linesearch/impls/morethuente/

include ${TAO_DIR}/bmake/tao_common

