
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = daapp.c daapp_solve.c daapp_monitor.c
SOURCEF  = 
SOURCEH  = daapp_impl.h dagridctx.h
OBJSC    = daapp.o daapp_solve.o daapp_monitor.o
OBJSF    = 
LIBBASE  = libtaopetsc
MANSEC   = daapp
LOCDIR   = src/petsctao/gridapplication/interface/

include ${TAO_DIR}/bmake/tao_common


