
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = bnls.c
SOURCEF  = 
SOURCEH  = bnls.h
OBJSC    = bnls.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/bound/impls/bnls/

include ${TAO_DIR}/bmake/tao_common

