
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lmvmmat.c taomat.c
SOURCEF  = 
SOURCEH  = lmvmmat.h 
OBJSC    = lmvmmat.o taomat.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = matrix
LOCDIR   = src/matrix/

include ${TAO_DIR}/bmake/tao_common


