
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  = 
SOURCEH  = 
OBJSC    = 
OBJSF    = 
DIRS2     =  include vector matrix indexset linearsolver application sys
DIRS    =  include gridapplication vector matrix indexset linearsolver application sys
LOCDIR   = src/petsctao/

include ${TAO_DIR}/bmake/tao_common


