
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = unit.c
SOURCEF  = 
SOURCEH  =
OBJSC    = unit.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/linesearch/impls/unit/

include ${TAO_DIR}/bmake/tao_common

