
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = tao_app.c tao_app_fg.c tao_app_j.c fdiff.c xmonitor.c oldroutines.c tao_app_util.c tao_app_monitor.c
SOURCEF  = 
SOURCEH  = tao_app_impl.h
OBJSC    = tao_app.o tao_app_fg.o tao_app_j.o fdiff.o xmonitor.o oldroutines.o tao_app_util.o tao_app_monitor.o
OBJSF    = 
LIBBASE  = libtaopetsc
MANSEC   = ptaopages
LOCDIR   = src/petsctao/application/petscapp/

include ${TAO_DIR}/bmake/tao_common


