
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = taovec_petsc.c pvec.c
SOURCEF  = 
SOURCEH  = taovec_petsc.h
OBJSC    = taovec_petsc.o pvec.o
OBJSF    = 
LIBBASE  = libtaopetsc
MANSEC   = ptaopages
LOCDIR   = src/petsctao/vector/

include ${TAO_DIR}/bmake/tao_common


