# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = cg.c
SOURCEF  = 
SOURCEH  = cg.h
OBJSC    = cg.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/unconstrained/impls/cg/

include ${TAO_DIR}/bmake/tao_common

