# $Id: makefile,v 1.1 2007-10-16 16:27:28 tmunson Exp $ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ntl.c
SOURCEF  = 
SOURCEH  = ntl.h
OBJSC    = ntl.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/unconstrained/impls/ntl/

include ${TAO_DIR}/bmake/tao_common

