
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taoapp_petsc.c taoapp_util.c
SOURCEF  = 
SOURCEH  = taoapp_petsc.h
OBJSC    = taoapp_petsc.o taoapp_util.o
OBJSF    = 
LIBBASE  = libtaopetsc
MANSEC   = ptaopages
LOCDIR   = src/petsctao/application/taoapp/

include ${TAO_DIR}/bmake/tao_common


