
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = boundproj.c
SOURCEF  = 
SOURCEH  = boundproj.h
OBJSC    = boundproj.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/linesearch/impls/boundproj/

include ${TAO_DIR}/bmake/tao_common

