
ALL: lib

#ADIC	    = /home/derivs/adic
#ADIC_ARCH  = linux

CFLAGS   = ${ADIC_INCLUDE}
FFLAGS   =
CPPFLAGS = 
SOURCEC  = adelement.c adelement2.c
SOURCEF  = 
SOURCEH  = taodaadic.h ad_deriv.h
OBJSC    = adelement.o adelement2.o
OBJSF    = 
LIBBASE  = libtaoadic
MANSEC   = daapp
LOCDIR   = src/petsctao/gridapplication/daadic/

include ${TAO_DIR}/bmake/tao_common


