
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gpcg.c gpcglinesearch.c
SOURCEF  = 
SOURCEH  = gpcg.h gpcglinesearch.h
OBJSC    = gpcg.o gpcglinesearch.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/bound/impls/gpcg/

include ${TAO_DIR}/bmake/tao_common

