ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = augmented.c
SOURCEF  =
SOURCEH  = augmented.h
OBJSC    = augmented.o
OBJSF    =
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/constrained/impls/augmented/

include ${TAO_DIR}/bmake/tao_common

