
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taois.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = taois.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = indexset
LOCDIR   = src/indexset/

include ${TAO_DIR}/bmake/tao_common


