# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bcg.c
SOURCEF  = 
SOURCEH  = bcg.h
OBJSC    = bcg.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/bound/impls/bcg/

include ${TAO_DIR}/bmake/tao_common

