# $Id$ 
include ${TAO_DIR}/bmake/packages

# OOQP_SUBDIR and APPSPACK_SUBDIR are defined in the above packages file

DIRS     = ${ESI_SUBDIR} ${OOQP_SUBDIR} ${APPSPACK_SUBDIR} ${GA_SUBDIR}

LOCDIR   = src/externaltao/

include ${TAO_DIR}/bmake/tao_common

