# makefile for libsidltao.so
ALL: lib

FFLAGS=
SOURCEF=
OBJSF=
MANSEC=

CPPFLAGS = ${TAO_SIDL_FLAGS_CXX}

OBJSC=taoapp_sidl.o
SOURCEC=taoapp_sidl.c
SOURCEH=taoapp_sidl.h
LIBBASE=libtaosidl
LOCDIR=src/sidl/interface/

include ${TAO_DIR}/bmake/tao_common

