# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lm.c
SOURCEF  = 
SOURCEH  = lm.h
OBJSC    = lm.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/least_squares/impls/cgnormal/

include ${TAO_DIR}/bmake/tao_common

