#! /bin/csh
# $Id: copytestlog,v 1.4 2000/03/22 19:58:19 balay Exp $ 
# 
# Copies log files from failed builds.
#

set RCP='scp -q -B -oProtocol=1'
source /sandbox/petsc/petsc-test/bmake/$1/buildtest

set RSYNC_DIR=`echo $TMP | sed 's%[^/][^/]*$%%' | sed 's%\/$%%'`
set TAO_DIR=$RSYNC_DIR/tao-test



if ( ! -r /home/petsc/logs/taologs/examples_$ARCH.$MACH.log ) then
  $RCP ${MACH}:$TAO_DIR/maint/examples_$ARCH.$MACH.log /home/petsc/logs/taologs
  chmod a+r /home/petsc/logs/taologs/examples_$ARCH.$MACH.log
endif
