
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = isils.c icp.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = isils.o icp.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/complementarity/impls/isls/

include ${TAO_DIR}/bmake/tao_common

