
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  = 
SOURCEH  = 
OBJSC    = 
OBJSF    = 
DIRS     =  interface element multigrid examples ${DA_ADIC_DIR} 
LOCDIR   = src/petsctao/gridapplication

include ${TAO_DIR}/bmake/tao_common


