
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC   = tvecdouble.c tvecsingle.c taovec.c
SOURCEC2 = taovec.c
SOURCEF  = 
SOURCEH   = tvecdouble.h tvecsingle.h
OBJSC     = tvecdouble.o tvecsingle.o taovec.o
SOURCEH2  = 
OBJSC2    = taovec.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = vector
LOCDIR   = src/vector/

include ${TAO_DIR}/bmake/tao_common


