
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = rscs.c
SOURCEF  = 
SOURCEH  =
OBJSC    = rscs.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/complementarity/impls/rscs/

include ${TAO_DIR}/bmake/tao_common

