
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  = 
SOURCEH  = 
OBJSC    = 
OBJSF    = 
LIBBASE  = libtaopetsc
MANSEC   = 
LOCDIR   = src/petsctao/application/
DIRS     = petscapp taoapp

include ${TAO_DIR}/bmake/tao_common


