
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = tron.c
SOURCEF  = 
SOURCEH  = tron.h
OBJSC    = tron.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/bound/impls/tron/

include ${TAO_DIR}/bmake/tao_common

