# $Id$ 

TAOSOLVERDIRS  = bound complementarity linesearch unconstrained
TAOOBJECTDIRS  = appobject matrix vector indexset lsolver
DIRS           = sys interface ${TAOSOLVERDIRS} ${TAOOBJECTDIRS} ${TAOPETSCDIR} externaltao fortran ${TAOSIDLDIR} 
SOURCEH        = tao_impl.h

LOCDIR   = src/

include ${TAO_DIR}/bmake/tao_common
