# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC1 =  fdifff.c tao_app_jf.c tao_appf.c taoapp_utilf.c daappf.c  daapp_solvef.c tao_app_fgf.c  tao_app_utilf.c  
SOURCEC2 =  newsolverf.c taof.c tao_fghjf.c  tao_utilf.c  tao_initf.c taoappobjectf.c
SOURCEC	 = ${SOURCEC1} ${SOURCEC2}
SOURCEF	 = 
SOURCEH	 = 
OBJSC1   =  fdifff.o tao_app_jf.o tao_appf.o taoapp_utilf.o daappf.o  daapp_solvef.o tao_app_fgf.o  tao_app_utilf.o  
OBJSC2   =  newsolverf.o taof.o tao_fghjf.o  tao_utilf.o  tao_initf.o taoappobjectf.o
OBJSC	 = ${OBJSC1} ${OBJSC2}
OBJSF	 =
LIBBASE	 = libtaofortran
MANSEC	 = solver
LOCDIR   = src/fortran/auto/

include ${TAO_DIR}/bmake/tao_common
