
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = projectedarmijo.c
SOURCEF  = 
SOURCEH  = projectedarmijo.h
OBJSC    = projectedarmijo.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/linesearch/impls/projectedarmijo/

include ${TAO_DIR}/bmake/tao_common

