
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bqpip.c
SOURCEF  = 
SOURCEH  = bqpip.h
OBJSC    = bqpip.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/bound/impls/bqpip/

include ${TAO_DIR}/bmake/tao_common

