# $Id$ 

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nls.c
SOURCEF  = 
SOURCEH  = nls.h
OBJSC    = nls.o
OBJSF    = 
LIBBASE  = libtao
MANSEC   = solver
LOCDIR   = src/unconstrained/impls/nls/

include ${TAO_DIR}/bmake/tao_common

