
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = multigridmat.c daapp_mgrid.c
SOURCEF  = 
SOURCEH  = multigridmat.h
OBJSC    = multigridmat.o daapp_mgrid.o
OBJSF    = 
LIBBASE  = libtaopetsc
MANSEC   = daapp
LOCDIR   = src/petsctao/gridapplication/multigrid/

include ${TAO_DIR}/bmake/tao_common


