ALL: lib


include ${TAO_DIR}/bmake/packages

CFLAGS   = 
CPPFLAGS = ${APPSPACK_INCLUDE}  -DHAVE_MPI
FFLAGS   =
SOURCEC  = taofevalmgr.C taofevalwkr.C apps_solver.C
SOURCEF  = 
SOURCEH  = taofevalmgr.h taofevalwrk.h apps_solver.h
OBJSC    = taofevalmgr.o taofevalwkr.o apps_solver.o
OBJSF    = 
LIBBASE  = libappspacktao
MANSEC   = 
LOCDIR   = src/externaltao/appspacktao
LIBS = 

include ${TAO_DIR}/bmake/tao_common


